#!/usr/bin/env python3
import os
import torch
# Workaround: force torch.load to allow checkpoint unpickling (weights_only=False)
# This avoids repeated "add_safe_globals" whitelisting for many TTS classes in checkpoints.
_orig_torch_load = torch.load
def _load_wrapper(f, *args, **kwargs):
	if 'weights_only' not in kwargs:
		kwargs['weights_only'] = False
	return _orig_torch_load(f, *args, **kwargs)
torch.load = _load_wrapper

from TTS.api import TTS

base = os.path.dirname(__file__)
sample = os.path.join(base, "sample_speaker.wav")
output = os.path.join(base, "test_cloned.wav")

print('Using sample:', sample)
tts = TTS(model_name="tts_models/multilingual/multi-dataset/xtts_v2", gpu=False)
print('Model loaded')

tts.tts_to_file(text="This is a cloned voice test generated by XTTS.", file_path=output, speaker_wav=sample, language='en', speed=1.0)
print('Cloned output saved to:', output)
